### ISSUE TITLE
Identify Audience for website

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#11]
### Overview
We need to know who we are designing this website for

### Action Items
- [x] Review the one sheet and pull out all the audience types and put in this issue
- [x] Identify audiences we have not named
- [x] Find user stories in the media in order to create personas 
- [x] Identify other people to ask including general channel
- [x] Create personas from validated user groups
- [x] Add user stories to new project board 

### Resources/Instructions
[BallotNav One Pager](https://docs.google.com/document/d/15tMTwUnPnfAeN1C4KP4mvGWaiz3IfkktTY4drKFa8eo/edit)

**Comment by kcoronel** [comment]
### Informed Voters 
Motivations
Folks looking for alternatives to mailing their ballot 

### ActiveSocialMedia Users 
Motivations 
Folks sharing BallotNav for wider use and reach 

### Voting Partner Organizations 
Motivations 
Sharing up-to-date direct information on ballot delivery

**Comment by myastark** [comment]
Voter Story:

Susie Sonneborn of Montclair, N.J., says she tried to be extra careful to make sure her ballot was postmarked on time when she voted in a mayoral race in May. But when she heard that more than 1,100 ballots — 9% of the total — had been rejected, she checked with the local election office and was shocked to discover that hers was one of them.

"It was just really disappointing and surprising that by following the instructions that are printed on the ballot, I was set up for failure," she says. Sonneborn insists that she didn't see anywhere that her ballot needed to be received within two days of the election to count, which was especially frustrating because the mayor's race was decided by only 195 votes. Residents held a rally outside town hall the day the new mayor was sworn in, calling for officials to "count every vote" in future elections.

[Signed, Sealed, Undelivered: Thousands Of Mail-In Ballots Rejected For Tardiness](https://www.npr.org/2020/07/13/889751095/signed-sealed-undelivered-thousands-of-mail-in-ballots-rejected-for-tardiness)

**Comment by myastark** [comment]
Facebook groups for validation
[Save USPS](https://www.facebook.com/groups/63943201801/)
[Vote by Mail - National](https://www.facebook.com/groups/VBMNational/)
[SAY NO TO MAIL IN VOTING](https://www.facebook.com/groups/2385831015053635/)
[Americans Against Mail In Voting](https://www.facebook.com/groups/573357583537144/)

**Comment by myastark** [comment]
More Audiences

Tired or Busy Voters
Motivations
To not have to think too hard  

Paranoid Voters
Motivations
Believe mail-in voting is a plot to execute a coup against the president but might choose an option that minimizes covid exposure compared to going to the polls, if they trust it

**Comment by Arjayellis** [comment]
Created a new project for user stories and personas https://github.com/hackforla/ballotnav/projects/2

**Comment by Arjayellis** [comment]
@kcoronel @myastark Just a reminder that I created a new project board for user stories. Please take a look (https://github.com/hackforla/ballotnav/projects/2) and feel free to add as we go.
