### ISSUE TITLE
HackforLA Website Write Up

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#357]
### Overview 
Write a write-up on BallotNav project for Hack for LA website standing site which will be utilizing UN's Agenda for Sustainable Development. 

### References 
[BallotNav Project One Sheet](https://docs.google.com/document/d/15tMTwUnPnfAeN1C4KP4mvGWaiz3IfkktTY4drKFa8eo/edit)

**Comment by kcoronel** [comment]
**Problem:** Due to COVID19 and cuts to the United States Postal Service, some voters may feel insecure not only about going out to the polls, but also about utilizing the mail to cast their vote. While it is possible to drop off your mail-in ballot in person, the rules for doing so are not clearly outlined in one single location. Information is scattered across state and county websites, each of which may individually fail to provide one or more elements of crucial information, such as available ballot drop-off times. 

**Solution:** The BallotNav project will collect this data through a network of brigade partnerships and update it accordingly leading up to the mid-term  elections in 2022. 

**Impact:** BallotNav is a project that will help voters quickly find the location, times of operation, and due date for dropping off mail-in ballots in person. Our goal is to provide information that helps voters cast their ballots safely and correctly, and avoid accidental disenfranchisement.

2030 UN Agenda for Sustainable Development 
**16.10** Ensure public access to information and protect fundamental freedoms, in accordance with national legislation and international agreements

@Arjayellis Bonnie told me that they are creating a site for current active projects with this theme problem, solution, impact, and un agenda sustainable development tenet and BallotNav would need a write up, feel free to edit the above :)

**Comment by Arjayellis** [comment]
Problem: There are currently numerous inconsistencies when it comes to accurate and up to date voter resources and ballot drop off information. While it is possible to drop off your mail-in ballot in person in most states, it remains an issue for voters due to distrust in the postal service, misguided information from the media, an inconsistent pool of resources provided by the government, and societal shifts from COVID-19. It is now more important than ever to have reliable resources for those hoping to have their voices heard.

Solution: The BallotNav project will collect and display this data through a network of brigade partnerships and update it accordingly in order to be utilized during elections across the US. 

Impact: BallotNav is a project that will help voters quickly find the location, times of operation, and deadline for dropping off mail-in ballots in person. Our goal is to provide information that helps voters cast their ballots safely and correctly, and avoid accidental disenfranchisement.

2030 UN Agenda for Sustainable Development
16.10 Ensure public access to information and protect fundamental freedoms, in accordance with national legislation and international agreements

**Comment by kcoronel** [comment]
@ExperimentsInHonesty Randall and I wrote this BallotNav summary in the format requested for HackforLA's website.

**Comment by Arjayellis** [comment]
@ExperimentsInHonesty Please review and let us know if we can close this out.

**Comment by kcoronel** [comment]
@Olivia-Chiong hello, we wanted to send over our write-up for the website according to UN's Agenda for Sustainable Development

**Comment by BrianCodes33** [comment]
Please take me off mailing list

**Comment by aNullValue** [comment]
Hi @BrianCodes33 , you're able to remove yourself from the group that gets notifications of activity. To do so, scroll to the top of this page, and toward the right hand side, near the top, there will be a drop-down that says "Unwatch". Click that drop-down box, and then select "Ignore". GitHub will then stop notifying you of activity in this repo.

**Comment by kcoronel** [comment]
thank you @BrianCodes33. Brian, Bonnie was going to reach out since you've forked things and you may lose that data. I'll ping her now to make sure she sends you the msg ASAP. thank you for your patience!

**Comment by Olivia-Chiong** [comment]
@kcoronel got it thanks!
