### ISSUE TITLE
Accomplishments Write-Up

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#358]
### Overview 
Create a write-up on what happened with the project and accomplishments to date 

### References 
[Updated BallotNav Project One Sheet](https://docs.google.com/document/d/1m6Dvw9D6eJhBCV5lLLlr0j27455F1BrAEclsWDePgnw/edit)

**Comment by kcoronel** [comment]
**Accomplishments:** 
- Recruited team of developers, designers, data scientists and volunteers 
- Developed product roadmap for product MVP design 
- Developers launched unique database for 
- Trained volunteers to validate collected data utilizing grassroots organizing. Covid19 has amplified the need for collective data validation such as validating information for testing and vaccination sites.  
- Validated voter data for Georgia's 2021 Special Election and launched product in time for GA mail in ballots

**Comment by Rabia2219** [comment]
This issue is being transferred to the following repo

- https://github.com/hackforla/admin-accomplishments/

It likely lose its labels and those will have to be recreated in receiving repo.

Here is a picture of what it had before the transfer.

![image](https://github.com/user-attachments/assets/fdc9d10f-67e9-445b-9a1a-15032ffb913b)
