### ISSUE TITLE
Develop MVP Document for 2022

### ISSUE THREAD

**Issue by kcoronel** [hackforla/ballotnav#447]
### Overview
Create a more finalized version, including the team's comments. 

### Action Items

- [ ] Update proposed MVP 
- [ ] Review with team 

### Resources/Instructions
[2021 Proposed MVP](https://docs.google.com/document/d/1TTQUDNSttQs1HU5z4IM9SIXeGvtCL_kJyiXZ2O4lkKE/edit)

**Comment by staceyrebekahscott** [comment]
Closed issue #430 as it was a duplicate of this issue.

**Comment by staceyrebekahscott** [comment]
Updated and assigned to myself, as I feel it relates to other issues assigned to me: #462 , #13.

**Comment by staceyrebekahscott** [comment]
Note from PM meeting with Bonnie on 02/19/22: As the [MVP proposal stands](https://docs.google.com/document/d/1TTQUDNSttQs1HU5z4IM9SIXeGvtCL_kJyiXZ2O4lkKE/edit)-packaging software and giving it away for jurisdiction to manage- can be an issue because it creates bad competitors and overpopulates the market.

**Comment by staceyrebekahscott** [comment]
@yoursgayathri Adding Gayathri to this issue. There needs to be a deeper understanding of where the backend is in order to further develop the MVP. I'd like to collaborate on this as this also connects with https://github.com/hackforla/ballotnav/issues/480, to be conducted by the UX team.

**Comment by kcoronel** [comment]
Issue is being closed as it will be the new year and we no longer need an MVP for 2022.
