### ISSUE TITLE
Collecting Customer Data (Customer Outreach, Calendly and Customer feedback) 

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/ballotnav#492]
### Overview
We will be collecting customer data via a posting on Reddit as our first approach, and will evaluate results based on the response. We will be asking for  people who work for any national voting org. 

*Changed issue title from "Reddit Posting" to "Customer Outreach" due to the inability to post on Reddit. 

### Action Items
- [x] Draft posting for Reddit, send to the team for review. 
- [x] Create Calendly account and add team members availability for interviews. 
- [x] Create template for collecting customer feedback.

**Comment by layneam** [comment]
Template for customer feedback is in Ballot Nav Shared Drive > Market Fit Research > Customer Development ([Link](https://drive.google.com/drive/folders/1unh54flAXwspRLh3sv0rYMkhJCpn5_65?usp=sharing))
Link: https://docs.google.com/spreadsheets/d/11lSWFNMLjr_zji3OMM2ReGFl9ZdG1dSfHtbYZiTjm6Y/edit?usp=sharing
Have added this link at the bottom of the customer interview questions doc at: https://docs.google.com/document/d/1fgngzGPxVUrLqKr5sYp4Uj5u1aPLeE6QeHz7xwEFL64 
cc: @kaerii

**Comment by layneam** [comment]
Calendly set up, link: https://calendly.com/ballotnav/voter-mobilization-research-interview?month=2022-06
![image](https://user-images.githubusercontent.com/20083861/172779351-055b5e70-6a8c-4c22-840c-d281d2beb534.png)

**Comment by staceyrebekahscott** [comment]
Posted in BallotNav Slack Channel by Layne 06/07/22:

My action item: reddit post. Here goes.
"Hello Redditors, I am working on a project for Hack for LA (link) and I'm asking for your help.

The project is about improving voter turnout in the USA, so we're looking to learn more about challenges and opportunities re: mobilizing US voters.

I'm looking to talk to people who work or volunteer regularly for national organizations that mobilize US voters as their core mission (think orgs like League of Women Voters).

Sound like you? Please fill out this short qualifying survey (link) and a researcher from our team will get in touch. Or if you know anyone who might be interested in talking to us, please forward them the survey.

Thank you!


ALSO: there are lots of Reddit channels :smile: Here are a few I found that might be good, if anyone has thoughts:
https://www.reddit.com/r/DemocraticUnderground/
https://www.reddit.com/r/VoteDEM/
https://www.reddit.com/r/GOTV2024/ (only has 3 members but I can't see anything more relevant so maybe they will have some leads)
https://www.reddit.com/r/electionreform/
https://www.reddit.com/r/USCensus2020/ (still quite active)


Replies to Post:

[Stacey (she/her)](https://app.slack.com/team/U02U9Q5DUF6)
  [1 day ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1654666952997159?thread_ts=1654656747.080779&cid=C0191KE1XB7)
I think the posting sounds good.

[Layne (AEST)](https://app.slack.com/team/U032H8FJX6U)
  [1 day ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1654667213157179?thread_ts=1654656747.080779&cid=C0191KE1XB7)
I think on reflection it should say something like "work boots-on-the-ground to mobilize voters" to disambiguate from [vote.org](http://vote.org/)? Maybe? (edited) 
:+1:
1

[Stacey (she/her)](https://app.slack.com/team/U02U9Q5DUF6)
  [1 day ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1654667451416289?thread_ts=1654656747.080779&cid=C0191KE1XB7)
Either way sounds fine.
:ok:
1

**Comment by staceyrebekahscott** [comment]
Posted in BallotNav Slack Channel by Layne 06/08/22:

[Layne (AEST)](https://app.slack.com/team/U032H8FJX6U)
  [8:34 PM](https://hackforla.slack.com/archives/C0191KE1XB7/p1654745684146709)
Ok, first roadblock: I don't have enough Reddit karma to post anything and they have a lot of measures in place to keep out new and inactive accounts. (It was worth a try!) I reckon we move to plan B, reaching out to our networks. Here's the text I prepared with links embedded:

"I am working on a project for [Hack for LA](https://www.hackforla.org/) and I'm asking for your help.

The project is about improving voter turnout in the USA, so we're looking to learn more about challenges and opportunities re: mobilizing US voters. I'm looking to talk to people who work or volunteer regularly for national organizations that mobilize US voters as their core mission (think orgs like League of Women Voters).

Sound like you? Please fill out this short [qualifying survey](https://forms.gle/bHwhqBFYjEgNFR1r9) and a researcher from our team will get in touch. Or if you know anyone who might be interested in talking to us, please forward them the survey: https://forms.gle/bHwhqBFYjEgNFR1r9

Thank you!"


Replies to Post:

[Layne (AEST)](https://app.slack.com/team/U032H8FJX6U)
  [1 day ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1654745731338499?thread_ts=1654745684.146709&cid=C0191KE1XB7)
I have a few people I know and will reach out to them now. I will also post in the HfLA general channel.
:+1::skin-tone-4:
1



[Karen (she/her/ella) (PST)](https://app.slack.com/team/U010KUGJATC)
  [16 hours ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1654780860591349?thread_ts=1654745684.146709&cid=C0191KE1XB7)
[@Layne (AEST)](https://hackforla.slack.com/team/U032H8FJX6U)
 let us know if we should also send this to people  :heart:


[Carrie Geng](https://app.slack.com/team/U035Q9CHQSH)
  [15 hours ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1654783737484499?thread_ts=1654745684.146709&cid=C0191KE1XB7)
How much reddit karma do we need to make a posting? I have something like 12 karma and if that’s enough, I could possibly try.


[Karen (she/her/ella) (PST)](https://app.slack.com/team/U010KUGJATC)
  [14 hours ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1654786810790119?thread_ts=1654745684.146709&cid=C0191KE1XB7)
I have 9 Karma


[Layne (AEST)](https://app.slack.com/team/U032H8FJX6U)
  [5 hours ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1654819890764499?thread_ts=1654745684.146709&cid=C0191KE1XB7)
I have no idea lol I googled it last night and there's no specific karma number listed. I think it's probably part of a trust algorithm and you just have to try to post. The button is grayed out when I try, but maybe you both will have better luck?


[Layne (AEST)](https://app.slack.com/team/U032H8FJX6U)
  [5 hours ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1654819937497789?thread_ts=1654745684.146709&cid=C0191KE1XB7)
I did manage to get a friend to agree to talk to me, I'm just working on finding a time that works with our timezones. So that's a good start!


[Layne (AEST)](https://app.slack.com/team/U032H8FJX6U)
  [5 hours ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1654820953999369?thread_ts=1654745684.146709&cid=C0191KE1XB7)
[@Karen (she/her/ella) (PST)](https://hackforla.slack.com/team/U010KUGJATC)
 Yeah I would say definitely let's get this out there and get appointments on the calendar!

**Comment by staceyrebekahscott** [comment]
@layneam I added the text from the postings in the BallotNav Slack channel to this issue, as we need a record in GitHub of the text we are using, and why we are switching to plan B- reaching out to our contacts.

**Comment by staceyrebekahscott** [comment]
[Layne (AEST)](https://app.slack.com/team/U032H8FJX6U)
 [Yesterday at 4:00 AM](https://hackforla.slack.com/archives/C0191KE1XB7/p1655031611270419)
Progress report:
Not that this should be a shock to anyone, but I'm not finding recruiting super-easy :sweat_smile:
I have two friends who have said they'd talk to me but haven't gotten them on my schedule yet. (One of them is Kent G who responded on our [Google Form](https://forms.gle/W6XbGEzYDyUwifLf6), I have followed up with him directly)
I've put out a blanket call on my personal Facebook, I know a bunch of GOTV organizers and am starting to ping them individually too. I'm trying more personal language in that outreach, e.g.: "Hey Jared, I definitely thought of you when writing this post. I'm hoping to build a product to help activists like yourself get more voters to the polls. Would you be willing to chat with me about your experience some time?"
I've also posted on [Craigslist](https://washingtondc.craigslist.org/doc/vol/d/dulles-getting-voters-to-the-polls/7495441419.html) using slightly different language to the Reddit post. (Backstory: I've been consuming some [materials](https://growth.design/case-studies) on psychology that have informed these language tweaks) I am locked out of Craigslist at the moment though because it can't verify my US phone number. If someone else can post in other major US cities, that might be easier.
I've pinged one social media account of a person I found working for a target org on LinkedIn. I think this will just be a numbers game.
LinkedIn Groups have been really fruitless, I wasn't able to find any groups that were very relevant.
My next actions will be searching for more people on LinkedIn and pinging their social media accounts, joining some Facebook Groups, and trying over at Movement Labs to see if they would be willing to help out. I might also try to participate in some phonebanking this week.
Finally, I think that even though picking a narrow target market is the right thing to do, we might struggle to get research participants unless we get an "in" with some networked contacts. So at the moment I'm not saying no to interviews where I can get them, even if they're not exactly our target, because I think it's worthwhile to network with them and we may find similar insights anyway.
Any constructive thoughts or feedback on this process are most welcome :upside_down_face: (edited) 
2 replies


[Carrie Geng](https://app.slack.com/team/U035Q9CHQSH)
  [7 hours ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1655125339955249?thread_ts=1655031611.270419&cid=C0191KE1XB7)
Thanks for all of your work Layne! I agree about the LinkedIn outreach--it’s actually not easy to find people. I wonder if it might be worth emailing the organizations themselves and ask if there’d be anyone there who can speak to us.


[Stacey (she/her)](https://app.slack.com/team/U02U9Q5DUF6)
  [< 1 minute ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1655150560320239?thread_ts=1655031611.270419&cid=C0191KE1XB7)
I have an idea for an approach that is in line with what Carrie is suggesting, that I got from a product management course on Udemy, and is in line with what Layne is thinking with a more direct approach. If we are at the point of trying something else, which it sounds like we are, I can put together an explainer of this idea to share with the group.

**Comment by layneam** [comment]
Progress report 14 June: 

I attended an LA Forward event today, it was a debrief about the recent CA primary election and it was pretty well attended, over 50 people I believe. It was very worthwhile hearing people talk about the GOTV context, what activities they're doing in this space, their successes and their frustrations.

I've also stoked a few conversations on Twitter and email with field organizers from Our Revolution. This will be a relatively slow process, but it is so far a lot better than cold outreach.

I started compiling my activity notes on a doc which I'll add to the ticket, thanks Stacey: https://docs.google.com/document/d/1AVk86a_4MsXkrCrV7tuqfZCeIgLR2CcP6k21kqLYuR8/edit?usp=sharing

**Comment by kaerii** [comment]
@staceyrebekahscott For emailing organizations, should I send emails from the BallotNav email or from my personal email?

**Comment by staceyrebekahscott** [comment]
[Layne (AEST)](https://app.slack.com/team/U032H8FJX6U)
 [Today at 1:18 AM](https://hackforla.slack.com/archives/C0191KE1XB7/p1655281085444979)
A few followup notes to today's meeting:
I've updated the [research spreadsheet](https://docs.google.com/spreadsheets/d/11lSWFNMLjr_zji3OMM2ReGFl9ZdG1dSfHtbYZiTjm6Y/edit#gid=0) with my notes from the LA Forward debrief (+ a couple nuggets I found on Reddit)
If you're looking for GOTV events to drop in on, I found the LA Forward event and Sister District using this [Google search](https://www.google.com/search?q=phonebank+for+progressive+candidates+usa), if you have other sources or ideas to share please do :slightly_smiling_face:
I'm attending Sister District's Northeast San Francisco monthly hub meeting tomorrow. Here's their [published strategy](https://sisterdistrict.com/strategy/), tagging [@Stacey (she/her)](https://hackforla.slack.com/team/U02U9Q5DUF6)
 as we were talking today about exactly this.
Here's the Opportunity Solution Tree [Miro template](https://miro.com/app/board/uXjVOsh7ca4=/) I showed today, this is my suggestion for how we can illustrate what our goal is (once we understand it better), how we're going to solve for it, and what options we considered along the way. (Source is Teresa Torres' book Continuous Discovery Habits)
I dug around in some of the old documentation and found this [Atlantic article](https://www.theatlantic.com/politics/archive/2014/01/why-are-the-poor-and-minorities-less-likely-to-vote/282896/) about obstacles the poor face to voting. Really interesting.
[@Stacey (she/her)](https://hackforla.slack.com/team/U02U9Q5DUF6) or [@Carrie Geng](https://hackforla.slack.com/team/U035Q9CHQSH)
 would either of you be happy to reach out to the people Drew told us about today, Sophia Alice or Mya Stark?
(edited)
2 replies

[Layne (AEST)](https://app.slack.com/team/U032H8FJX6U)
[12 hours ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1655285376424109?thread_ts=1655281085.444979&cid=C0191KE1XB7)
Some events I found that look interesting, if anyone wants to attend:
https://www.mobilize.us/ptp/event/438690/
https://events.democrats.org/event/404981/
https://www.mobilize.us/indivisiblefloridanetwork/event/416098/
https://www.mobilize.us/indivisiblefloridanetwork/event/402442/
https://act.indivisible.org/event/local-actions/164208/signup/
https://act.indivisible.org/event/local-actions/166150/signup/
(more Indivisible events [here](https://indivisible.org/events?type=Virtual))
(edited)

[Karen (she/her/ella) (PST)](https://app.slack.com/team/U010KUGJATC)
  [4 hours ago](https://hackforla.slack.com/archives/C0191KE1XB7/p1655314199227769?thread_ts=1655281085.444979&cid=C0191KE1XB7)
[@Stacey (she/her)](https://hackforla.slack.com/team/U02U9Q5DUF6) [@Carrie Geng](https://hackforla.slack.com/team/U035Q9CHQSH)
 let me know if you want me to make intros to Sophia or Mya :slightly_smiling_face:

**Comment by staceyrebekahscott** [comment]
@kcoronel Thank you for the help here. Yes, please make the connection for Mya and Sophia to both myself and Carrie. 

@kaerii Based on our availability we can discuss who follows up with Sophia or Mya.

**Comment by kcoronel** [comment]
@kaerii adding here the information for BallotNav gmail access. 

First, go [here](https://hackforla-team.1password.com/) and sign in. If you’ve misplaced your password, please choose to recover your password. If you are able to sign in, please head to vaults and search for ballot nav, on the left hand side you will see something that says view vault, review this for the gmail folder which has our gmail login, and then login to ballotnav.

**Comment by staceyrebekahscott** [comment]
[Layne (AEST)](https://app.slack.com/team/U032H8FJX6U)
  [8:09 PM](https://hackforla.slack.com/archives/C0191KE1XB7/p1655348979442859)
I had fun at the Sister District Northeast San Fran meeting just now; there wasn't as much discussion about pain points or challenges but I did get some insights into how they approach voter turnout. We practiced having conversations with voters using a "3 Vs" framework; they told me about their strategy to energise state and local races because voting local pretty much guarantees voting up-ballot too; and they work to find undecided voters for targeted outreach from the candidate. I've added these to the [research spreadsheet](https://docs.google.com/spreadsheets/d/11lSWFNMLjr_zji3OMM2ReGFl9ZdG1dSfHtbYZiTjm6Y/edit#gid=0).

**Comment by staceyrebekahscott** [comment]
@layneam Great insight on the spreadsheet from the LA Forward and Sister District meetings. Thank you for attending those and taking such detailed notes. 

My initial thoughts from this are:
- Voters need better resources in one place for finding out about all of the candidates, especially judges and controllers (roles that are a bit more obscure and unfamiliar to the average, low information voter. 
  - I would guess a vast majority of voters felt very intimidated by the 8 page ballot in CA. 
- Field organizers need a way to more easily train volunteers, and it should include ways to combat the emotional difficulties that come from phone and text banking. 
- Voters and organizers need alternative ways to connect. Hosting ballot parties or other types of gatherings, like a caucus without the candidates, (Evite but for voting parties?)

**Comment by layneam** [comment]
More events to check out:
- All In Challenge: https://allinchallenge.org/resource-hub/webinar-series/ (The next event is Increasing Voter Turnout at Community Colleges Thursday, June 23 from 2:00 – 3:30 PM ET and there are older recordings available as well)
- Democracy North Carolina: https://democracync.org/events/ (Next event is Early Voting Advocacy Training on 23 June 6-7.30PM ET)
- Swing Left/Indivisible South Bay June 26 2022 @ 2:00 pm - 3:30 pm PDT: https://socalblue.org/event/swing-left-indivisible-south-bay-meeting-time-tba/2022-06-26 (pretty packed calendar on this site, worth sifting through)
- "Fridays at 4" Letter Writing https://www.mobilize.us/bluefuture/event/274619/ <-Since this is an activity, it might yield more opportunity to ask questions and build relationships with people
- Lucha team meeting (Sister District Partner) Wed, Jun 22 @ 6pm MST https://www.mobilize.us/luchaaction/
- And a list of other affiliates to check out: https://www.populardemocracy.org/our-affiliates

**Comment by layneam** [comment]
> @layneam Great insight on the spreadsheet from the LA Forward and Sister District meetings. Thank you for attending those and taking such detailed notes.
> 
> My initial thoughts from this are:
> 
> * Voters need better resources in one place for finding out about all of the candidates, especially judges and controllers (roles that are a bit more obscure and unfamiliar to the average, low information voter.
>   
>   * I would guess a vast majority of voters felt very intimidated by the 8 page ballot in CA.
> * Field organizers need a way to more easily train volunteers, and it should include ways to combat the emotional difficulties that come from phone and text banking.
> * Voters and organizers need alternative ways to connect. Hosting ballot parties or other types of gatherings, like a caucus without the candidates, (Evite but for voting parties?)

@staceyrebekahscott Lots and lots of opportunities here, holy cow. Hopefully by attending more meetings and asking thoughtful questions where possible, we can start teasing out common themes. Thanks for your feedback, I think those are some good problem statements. I like the idea of synthesizing insights into customer needs (as you've done) and keeping them somewhere. I will have a think about the best way to do that.

**Comment by staceyrebekahscott** [comment]
Before posting on the Slack channels, I reached out to Stephanie from Civic Tech Jobs via Slack, as she posted a survey on the channels recently, and I wanted to see what feedback she had on the process before posting.

**Comment by layneam** [comment]
@staceyrebekahscott I can't find the other org that had previous meeting recordings readily, but the All In link should have enough to keep some folks busy for the moment, thank you for taking a look.

re: adding insights to a tab, that does sound like an obvious and simple solution. But I would also like to be able to track what exactly we heard/read/saw that led to that insight, and how often it's come up. I would also like to make sure we consider different ways to frame the same opportunity. So as much as I love centralising our work, there might be tools that could work better than a spreadsheet tab. Like Airtable? Or a mind map in Miro?

Some other orgs with affiliate links to research, @kaerii if you don't have enough orgs to email I'm finding lots :) :
- https://866ourvote.org/partners/
- https://nationalvoterregistrationday.org/2022-partners/

**Comment by staceyrebekahscott** [comment]
I looked into the website All In Campus Democracy Challenge, focused on mobilizing college students. I reviewed 2 reports:
[Strengthening American Democracy: A guide for developing an action plan to increase civic learning](https://allinchallenge.org/wp-content/uploads/StrengtheningAmericanDemocracyGuide_VOL3.pdf)
[2022 All In Campus Action planning report](https://allinchallenge.org/wp-content/uploads/2022-1st-Action-Plan-Submission-Opportunity-Report.pdf)

Neither report yielded any specific insight, but they lay out a process we can use for a report or guide or case study. But the Action Plan guide listed the [Andrew Goodman Foundation](https://andrewgoodman.org/) as having used their planning tool, which led me to the [Vote Everywhere Ambassador Handbook](https://andrewgoodman.org/wp-content/uploads/2020/09/VE-Ambassador-Handbook-FL-2020.pdf). This includes case studies, which I am still reviewing for insights.

**Comment by layneam** [comment]
I am signed up for these events:

- [Indivisible Sonoma County Out-of-District Meeting](https://act.indivisible.org/event/local-actions/166150/signup/) Monday, June 20, 6:00 PM
- [Happy Hour - Every Friday - Where we talk about Stuff of the Week](https://act.indivisible.org/event/local-actions/164208/signup/?akid=&zip=&source=) Friday, June 24, 5:45 PM
- [DEFEND OUR CIVIL and VOTING RIGHTS](https://www.mobilize.us/indivisiblefloridanetwork/event/402442/) Sun, Jul 10, 8:00pm–9:00pm EDT
- [Learn (on Zoom) to Register PA Democrats (In Person)!](https://events.democrats.org/event/436167/) Wed, Jul 6, 7:00pm–8:00pm EDT
- [We Are All Organizers: Community Organizing Host Training!](https://events.democrats.org/event/404981/) Tue, Jun 21, 7:30pm–9:00pm EDT
- [2022 Indivisible Group Leader Convention!](https://events.zoom.us/ev/DOzZ50MgsgrENdA59QAAFgAAAIrwOZueGdVp5xFVWLWXdnIsF-16UE1Zatba8xzo6G8hTOEoIO_D~APqdknpVUHnUJCPLY1djCWUp8LbVFnoCU22g_iM) Jul 12, 2022, 7:00 PM New York
- [Fridays at 4 (4 pm Pacific/7 pm Eastern) Letter Writing](https://www.mobilize.us/bluefuture/event/274619/) Fri, Jul 1, 4:00pm–5:30pm PDT
- [East Valley Team Meeting](https://www.mobilize.us/luchaaction/event/464062/) Wed, Jun 22 @ 6pm MST

The first one on the list will conflict with our usual product manager meeting, @staceyrebekahscott and @kcoronel. Should we cancel this week or move it? I can't meet directly before the team meeting either because of the fifth event on this list :) But we can find some time before or after if you like.

I think the main focus is just fact finding at this point, but it would be nice if we had more volume of data coming in faster.

**Comment by staceyrebekahscott** [comment]
Created new issue #494 to address further progress on emailing organizations for interviews, assigned issue to @kaerii

**Comment by layneam** [comment]
Continuing on this thread per Stacey's comment `I am in the process of creating some new issues, breaking up issue # 492 into smaller chunks- the comments are getting very long. Layne- I think you should continue posting all of your work in issue # 492.`

Attended [Individisible Sonoma County Out of District Meeting](https://www.mobilize.us/indivisiblesonomacounty/event/446687/). 
**Background info:**
- July is looking like a 'quiet month' for this group. It sounds like they are waiting to hear back from campaigns in their target states/districts to try and coordinate activities. I guess this makes sense because some candidates are fresh off of the Dem primary elections.
- They do postcards, canvassing, and phonebanking for candidates.
- In their meeting they talked in fair detail about the races they're watching in CA, NV & AZ and why those races are important. They mentioned one or two races they're *not* paying attention to because they're safe Republican.
- Some members mentioned other orgs they're working with in tandem, e.g. https://www.activateamerica.vote/campaigndigest So, it looks like they're bouncing around and cross-pollinating with other groups who have active campaigns going.
- There was one new couple, other than me, on the call. They had been contacted by a door-to-door canvasser and were politically aligned so they showed up to the call today. They are a musician couple and suggested doing a joint event with Individisible at a popular coffee shop.
**Challenges:**
- There is a lot of concerned talk from Indivisible volunteers (according to the organizer) that voter turnout is so low this primary season. The organizer pointed out that turnout so far is 31%, which is lower than the 32.85% average, but still in the ballpark. He expressed they should work to turn out voters in the general election and that the Equal Rights Amendment will be on the Nevada ballot, which should drive a higher number of voters. 
- There was a fair bit of talk about 3rd parties and whether they will harm Dem turnout. There is a 3rd party the American Independent party, which because of its confusing name, causes some people who are registering to vote as "unaffiliated" to register for the party uninentionally. This is a problem because American Independent party is a right wing extremist party that may send materials to the "unaffiliated voter", and other parties won't try to contact the voter.
- Postcarding is incredibly popular with volunteers - an organizer signed on one Unitarian Universalist church and two synagogues this month to participate. However, these religious orgs can't send partisan messages and many other volunteers refuse to do it. So this Indivisible organizer has lots of partisan "blunt" postcards, which she thinks is an important message to voters, but she can't get many volunteers to write them. (Aside: I've seen [other articles](https://www.everyday-democracy.org/tips/7-tips-can-boost-your-organizing-efforts) claim that positive messaging is more effective than negative messaging)

Will add some of these insights to the [research spreadsheet](https://docs.google.com/spreadsheets/d/11lSWFNMLjr_zji3OMM2ReGFl9ZdG1dSfHtbYZiTjm6Y/edit#gid=0)

**Comment by layneam** [comment]
Attended [Movement Labs Weekly Training](https://us06web.zoom.us/meeting/register/tJIvce2srTwqHdIfcSCnVbGE1_s-Fl80lnlZ).
**Background info**
- Movement Labs hosts volunteer driven textbanking for progressive orgs like Black Voters Matter, Contest Every Race, Defend Democracy, regional branches of the Democratic party, etc. View a list of current and upcoming campaigns [here](https://movementlabs.com/text). 
- The organizations pay a fee to Movement Labs to host and staff the textbanking effort. The orgs work with a salesperson/account manager to develop the script toolkits, see example [here](https://docs.google.com/document/d/14GcP1Uh8aLtV_hhAbV3XyswtboySXYTZXhPDghm4C3s/edit). 
- Movement Labs uses a text messaging system called [Spoke](www.spoke.live) to manage texts and replies in a threaded conversation. Volunteers and staff send text messages. They rely heavily on Slack to announce active textbanking campaigns and to provide real time support to volunteers who might get questions from the person they text that they can't answer.
- They don't have hard numbers on the impact of their campaigns on voter turnout, only general (publicly available) data about the efficacy of text messaging. Anecdotally the trainer told me that a campaign they worked on reported a 4x turnout increase after implementing textbanking (I think this might have been for an event, not for an election). Movement Labs measures success as "positive responses" such as "yes" responses from their campaigns, link clickthroughs, and RSVPs.

**Challenges:**
- When setting up a campaign in Spoke, if a list needs to be changed for any reason, no edits are allowed to the list. The entire campaign needs to be rebuilt. (The trainer mentioned she "understands why" but I didn't probe that part. I would speculate it has to do with accidentally losing/malicious deleting records of conversations?) This presumably takes a long time and is frustrating.
- Spoke's bandwidth is an issue. Movement Labs has crashed the software many times on larger campaigns. This can cause volunteers to get frustrated and go elsewhere, even though the outages are usually brief, like a few seconds.

**Comment by layneam** [comment]
Attended [We Are All Organizers: Community Organizing Host Training](https://events.democrats.org/event/404981/)
**Background info**
- The goal of "Organizing Everywhere", a project of the DNC, is to build capacity for volunteers in all 50 states to activate relational networks whenever needed. https://www.youtube.com/watch?v=Ev8av5bKupQ
- Here's a [list of resources](https://docs.google.com/document/d/1uNeLl5OdOWzGByxP11DLkzFI6Lcx2zE7/edit) from the call. 
**Challenges**
- Recruitment, getting people to be as passionate, building a community who are just as serious as the recruiter. Volunteers often flake out.

**Comment by layneam** [comment]
Attended [Overcoming the Rural-Urban Divide Pt 2](https://www.eventbrite.com/e/overcoming-the-rural-urban-divide-a-training-for-indivisible-june-15-22-registration-325285596977)
**Background info**
- This is part 2 of the Overcoming the Rural Urban Divide talk; the first part is here: https://www.youtube.com/watch?v=mhkXe6fxhsE
- The talk was really about how Democrats need to change their thinking, language and approach to appeal to rural voters. 

**Challenges**
- Rural voters have been turning away from the Democratic party because they perceive its members to be condescending and uninterested in their concerns. 
- Politicians and activists who try to talk to rural voters don't always understand how rural values differ from "urban mainstream" or lefty values. They tend to talk too much, frame the issues in a way that rural voters can't relate to, and judge or persuade without establishing common ground or rapport.
- Rural voters didn't necessarily turn out in record numbers in 2020. Only 35-40% of eligible African American men voted. They express not feeling like they are being heard. Some community groups are making an effort to listen to them and get them to pledge to vote.
- When I asked how GOTV activists can be better supported in conservative rural areas, the answer the panel gave was to build organizing structure which will bring people out of the woodwork. Lefty types can think they're the only ones in their town, but there are always more than they realize. Working together can make isolated people feel like they have purpose and fit.

**Comment by layneam** [comment]
My computer took a crap last week and I lost all my notes, sorry for the wait. Here are the meetings I went to in the past 2 weeks.

1. [Listening Session for Native American Voices](https://www.eventbrite.com/e/listening-session-for-native-voices-tickets-354116069697) by the Oklahoma Policy Institute
- A general session to hear about issues in the community, not voting specific
- Major themes: mental health, unemployment & people leaving due to lack of opportunity on reservations, lack of connections/representation when decisions are being made in the state capital, criminalization (of women), tribal capacity/coalition building, lack of trust & discrimination in healthcare, health & ADHD issues in young people

2. [We Are All Organizers Toolkit Training](https://events.democrats.org/event/458043/) by the Democratic Party
- A followup to the relational organizing training I did the week prior, we went through how to use the Democrats' Mobilize account to create community events. Anyone can create an event and, subject to approval, it will be publicized on the DNC's Mobilize event feed for folks in the area to find.
- Some event templates exist, [e.g.](https://events.democrats.org/c/dnc-pride-2022/event/create/?event_creation_source=discovery_page_no_commit)
- [Organize Everywhere Toolkit Training doc](https://docs.google.com/document/d/1uNeLl5OdOWzGByxP11DLkzFI6Lcx2zE7/edit)

3. [Indivisible Rural Caucus June Call](https://indivisible.zoom.us/meeting/register/tZMsf-mpqjkqG9B9_O6Box8z73cHfZTMi3L7)
- Requests for future topics, major themes: poll watching, safety/de-escalation, messaging, re-energizing voters & volunteers (see chatbox link below for full text)
- [Recording](https://indivisible-dot-yamm-track.appspot.com/1MFdqGijBtde6nDkd2UaFwnhAFShjlXyPbxiicsROyodGoXm2gQG0U4aYKYLjdTP5ie7kIUbLIHQGbN8CQitIid__aIlstZTsPe2q3lTA9gu_Rz5nQFVsa3pbPXTEGxzh02YuKfUwViDMbdzQh5xRwlPCJPUxghh2Yy2Qun6Derpg0fbseS5sHDk-h3zehW3LRDek-JY4--m-WNubHa94yZPNUrtFTr5rbRv62OdjXzQlSKM04XnnIx5S3WDPDlAlKVkl)
- [Slides](https://indivisible-dot-yamm-track.appspot.com/13cwXZ08gwEDTRu-3cU85RwEJ71TatWuhUKfBgyuQkOBIoXm2gQGx5N8HRYk_F-aoUM50RKDdgf9ioobSkVCxc-PqJ5VtqUt-9ZfmyRCP5Ho-sMCqNKaAxT0N_CwNiNQQ89ioupksc5M1iQLDgSK97YVbUh6thAz6RImpxOcS8ax5tnB9Hdi2qfkYvcJoGshXuvcNn0vIVDIrZjIsew)
- [Ready the Ground - Movement Marshaling handout](https://indivisible-dot-yamm-track.appspot.com/1kfKKVeClY8U7Kv6P5oTJOmRKLjfvvew701yBYxZSKeBKoXm2gQEFSQi-P8Ro-V9e4pGQ9MbHnsjovwS5cGPyOBfnha1P5UxHLVEgXHPWw2nLLPryp_ErxeEN3SZZdtUelUcJVLTQDCfguC-wRWddpmnT5yBm0wkkjRLH5URhcET62nGeNzftfrSB2C1WcUdU4UW69F8E94VqWFseY72p)
- [All Links mentioned in Call](https://indivisible-dot-yamm-track.appspot.com/1s4Ka2dlrc1FYs1vnB7DnFJfrHdsCkR7-2HC_F7gfqZtMoXm2gQFl9IlRm_TxcxJvXXZR8gmGgM0u4_2VA1D8eGXIQpfPHqNhqThi5Iw7L6mjQWkqG7eI8QD_T3sgYE4zfEvhWsb2-xKqhHSVGn3Zry1MU3pWYfBhODLvDiW7ni5X-oCj_W6Pl1rmvs4EMJLbbOASTFBrw8qKGafVhvE) (PLEASE DO NOT MISS THIS RESOURCE)
- [Chatbox Link](https://indivisible-dot-yamm-track.appspot.com/1Q3qtbS7UCLmZmQD52RX_nByRxCwRvHlVjWpvnOayHuFOoXm2gQG5GrhcRrKKrsJESFOfk9dYJFfpZMQ3YkYHxPACV7jOXa07ffGMzpNhsTYz90KWnUFL1XMCI8ehsAarES9bVaXVvGhdiLibZVkVxLq3zVwwypIfe6ADgU8JDVAstcW1gKAvOKAKrmzfLSwQk1D9ExFDY_7lZcRHr7Ht)

4. [Fridays at 4 Swing Left letter writing](https://www.mobilize.us/swingleft/event/274619/)
- I did these for the past 2 weeks. They say in 2020 their 17.8 million postcards improved voter turnout by .8% nationwide.
- Messaging and recruiting/retaining leaders and volunteers are the most important concerns of this group.

5. [Field Team 6 PA Voter Registration Training](https://events.democrats.org/event/436167/)
- This group developed a website [Voterizer.org](https://voterizer.org/) to help canvassers register voters in all 50 states; mostly it just links to SOS websites. It has some limited [customization options](https://www.youtube.com/watch?v=xSbqzxgdcQM).
- The training walked individual volunteers through their "[voter drive in a box](https://www.fieldteam6.org/)". [YouTube video](https://www.youtube.com/watch?v=b1enGZYtkLo)
- Lots of questions in the chat about logistics, major themes: how to register voters in other states? (laws vary wildly so trainings must be state-specific) how to deal with multiple confusing online/paper voter registration forms from the state? how to handle voter data? where can we register voters and do we need to get permission from the property owner?

**Comment by staceyrebekahscott** [comment]
Websites discussed during call with Sophia Alice re: Data collecting/ analysis and voter mobilization. 

https://www.bluebonnetdata.org/

https://www.civisanalytics.com/

https://catalist.us/

https://targetsmart.com/

https://movementcooperative.org/

https://github.com/move-coop/parsons

https://generationdata.org

https://twitter.com/thebmbennett

https://twitter.com/thebmbennett/status/1541572154856194050

**Comment by kcoronel** [comment]
Closing this issue because it looks like all tasks have been completed
