### ISSUE TITLE
Emergency Action Notifications Examples

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/ballotnav#67]
### Overview
We need a notification examples so that design can plan them in.

### Action Items
- [x] Link or paste the messages into the comments below

**Comment by aNullValue** [comment]
From a few minutes of browsing only the historical Directives of the Ohio Secretary of State, these particular directives may be relevant examples of things that BallotNav should be able to reasonably display.

A single county is ordered to remain open late; all other counties are prohibited from releasing election results until that time lapses. [Link](https://www.ohiosos.gov/globalassets/elections/directives/2015/dir2015-21.pdf) [Link](https://www.ohiosos.gov/globalassets/elections/directives/2008/dir2008-37.pdf)

Multiple counties ordered to remain open; all other counties prohibited from releasing results. [Link](https://www.ohiosos.gov/globalassets/elections/directives/2016/dir2016-09.pdf)

Specific precincts in a single county ordered to remain open. All other jurisdictions prohibited from releasing results. [Link](https://www.ohiosos.gov/globalassets/elections/directives/2007/dir2007-24.pdf)

Judge orders the eligibility of voters age 17 in primary election in Ohio. [Link](https://www.ohiosos.gov/globalassets/elections/directives/2016/dir2016-08.pdf)

Ohio counties ordered to accept applications for absentee ballots from unregistered voters, and subsequently issue a provisional ballot rather than absentee ballot. [Link](https://www.ohiosos.gov/globalassets/elections/directives/2016/dir2016-37.pdf)

Court orders counties to issue absentee ballots upon request during an extended period of time for persons who were jailed. [Link](https://www.ohiosos.gov/globalassets/elections/directives/2014/dir2014-33.pdf)

Substantial amendments to provisional ballot eligibility for homeless and others. [Link](https://www.ohiosos.gov/globalassets/elections/directives/2010/dir2010-73.pdf)

Revises interpretation of validity of applications for absent voter ballot. [Link](https://www.ohiosos.gov/globalassets/elections/directives/2008/dir2008-93.pdf)

Instructions to counties from Secretary of State in anticipation of court orders that may substantially impact operations. [Link](https://www.ohiosos.gov/globalassets/elections/directives/2008/dir2008-60.pdf)
